Support serializing Option<chrono::DateTime<_>> as Option<bson::DateTime>
mongodb/bson-rust pull request #482
Opened 2024-07-06 01:30 UTC by lazureykis

2024-07-09 15:42 UTC, isabelatkinson commented
Hi @lazureykis, thanks for opening this PR! Can you please add some tests for this functionality to [this file](https://github.com/mongodb/bson-rust/blob/main/src/tests/serde.rs)?

2024-07-10 22:07 UTC, isabelatkinson requested changes
Looks like there are some formatting errors. You can run the `check-rustfmt.sh` script in the `.evergreen` directory to determine where the errors are coming from and then use `rustfmt +nightly --unstable-features <filename>` to fix them.

2024-07-10 22:07 UTC, isabelatkinson commented on src/serde_helpers.rs
> +/// Contains functions to serialize a [`Option<chrono::DateTime>`] as a [`Option<crate::DateTime>`] and deserialize
```suggestion
/// Contains functions to serialize an [`Option<chrono::DateTime>`] as an [`Option<crate::DateTime>`] and deserialize
```

2024-07-10 22:07 UTC, isabelatkinson commented on src/serde_helpers.rs
> +/// a [`Option<chrono::DateTime>`] from a [`Option<crate::DateTime>`].
```suggestion
/// an [`Option<chrono::DateTime>`] from an [`Option<crate::DateTime>`].
```

2024-07-11 17:36 UTC, lazureykis commented
> Looks like there are some formatting errors. You can run the `check-rustfmt.sh` script in the `.evergreen` directory to determine where the errors are coming from and then use `rustfmt +nightly --unstable-features <filename>` to fix them.

Thanks. Should be fixed now.

2024-07-12 21:43 UTC, isabelatkinson approved these changes
looks great - going to tag in the other team member for approval and then we can merge this in! thanks for the contribution!

2024-07-15 15:06 UTC, merged