Impl Hash/Eq for BSON
mongodb/bson-rust pull request #495
Opened 2024-09-03 06:12 UTC by NineLord

#494
Summery of changes:
* Added feature `hashable` to require the user to choose to opt-in using `Bson` as hash key.
 Although, `serde_json` didn't bother with having this behind the feature flag, so If you like I can remove it.
* `Bson::Double(f64)` - implemented the same solution as [`serde_json`](https://docs.rs/serde_json/1.0.127/src/serde_json/number.rs.html#53-70).
* `Bson::Document(Document)` - implemented the same solution as [`serde_json`](https://docs.rs/serde_json/1.0.127/src/serde_json/map.rs.html#395-397).
* `Bson::JavaScriptCodeWithScope(JavaScriptCodeWithScope)` - Able to impl Hash/Eq only if Document is impl Hash/Eq.
* `Bson::{RegularExpression(Regex), Binary(Binary), Decimal128(Decimal128), DbPointer(DbPointer)}` - Added Derive Hash/Eq without feature flag `hashable`, no reason for it not to implement those by default.
* Added unit test to show that using Bson as key works.

I didn't implement it yet, but if the above feature is acceptable,
it might be worth adding another feature like `not(preserve_order)` from `serde_json`,
to change `Bson::Document` to use `BTreeMap` instead of `indexmap` for more efficient hashing.
I don't mind adding this as a separate PR.

2024-09-03 18:05 UTC, abr-egn approved these changes

2024-09-03 18:06 UTC, abr-egn commented
Thank you for the well-thought-out PR!  The changes look good to me and I've started a test run; once the tests pass and this is reviewed by another team member we'll merge it in.

2024-09-03 18:08 UTC, abr-egn commented
On the topic of switching `Document` to use `BTreeMap`, I'm a bit more hesitant, but if you have the time to put together a PR and a basic benchmark it's certainly something we'd consider 🙂

2024-09-04 21:03 UTC, isabelatkinson requested changes
a few docs suggestions, otherwise looks good. thanks for your contribution!

2024-09-06 15:31 UTC, isabelatkinson approved these changes

2024-09-06 15:31 UTC, merged